<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HC.GeoBore</RootNamespace>
    <AssemblyName>GeoBore</AssemblyName>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <Product>GeoBore</Product>
    <AssemblyTitle>GeoBore</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
  </ItemGroup>

</Project>
